name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - v2.0_discord.py

  # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: raphael-bot

jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    # Running this job only for main branch's push event
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: raphael-bot
        dockerfile: Dockerfile

  build-and-publish-tag:
    runs-on: ubuntu-latest
    # Always make a package with each git
    if: ${{ always() }}

    steps:
    - uses: actions/checkout@v2

    - name: Build and Publish Tag Docker image
      uses: VaultVulp/gp-docker-action@1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: raphael-bot
        dockerfile: Dockerfile
        image-tag: ${{ github.run_id }} # Unique number for package
